css:
  enabled: true
  src:
    - scss/*.scss
  dest: dist/
  flattenDestOutput: true
  lint:
    enabled: true
    failOnError: true
  sourceComments: false
  sourceMapEmbed: false
  outputStyle: expanded
  autoPrefixerBrowsers:
    - last 2 versions
    - IE >= 9
  includePaths:
    - ./node_modules
js:
  enabled: false
  src:
    - js/**/*.js
  dest: dist/
  destName: all.min.js
  sourceMapEmbed: false
  uglify: false
  babel: false
  eslint:
    enabled: true
    src:
      - js/**/*.js
      - gulpfile.js
patternLab:
  enabled: true
  src:
    root: brand_one/
    source: pattern-lab/source/
browserSync:
  enabled: true
  port: 8080
  watchFiles: null
  baseDir: ./
  startPath: pattern-lab/public
  openBrowserAtStart: true
  browser:
    - Google Chrome
  tunnel: false
  reloadDelay: 50
  reloadDebounce: 750
